// packages/themes/kidsmile-dental-care/components/sections/Services.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useModalStore } from '~~/packages/base/app/stores/modal'
import { ArrowRight, Sparkles, Shield, Heart, Smile, Check } from 'lucide-vue-next'

const modalStore = useModalStore()
const apiServices = ref<any[]>([])

async function fetchServices() {
  try {
    const res = await fetch('/api/services/public')
    if (res.ok) {
      const data = await res.json()
      if (Array.isArray(data) && data.length > 0) {
        apiServices.value = data
      }
    }
  } catch (e) {
    // Graceful fallback to static translated items
  }
}

onMounted(() => {
  fetchServices()
})

const defaultPrograms = [
  {
    id: 1,
    titleKey: 'services.service1Title',
    ageKey: 'services.service1Age',
    descKey: 'services.service1Desc',
    bgClass: 'bg-amber-50/80 border-amber-200/80 hover:bg-amber-100/60',
    badgeClass: 'bg-amber-100 text-amber-900 border-amber-300',
    iconBg: 'bg-amber-400 text-amber-950',
    iconEmoji: '🍼',
    accentColor: 'text-amber-600'
  },
  {
    id: 2,
    titleKey: 'services.service2Title',
    ageKey: 'services.service2Age',
    descKey: 'services.service2Desc',
    bgClass: 'bg-rose-50/80 border-rose-200/80 hover:bg-rose-100/60',
    badgeClass: 'bg-rose-100 text-rose-900 border-rose-300',
    iconBg: 'bg-rose-400 text-white',
    iconEmoji: '🛡️',
    accentColor: 'text-rose-600'
  },
  {
    id: 3,
    titleKey: 'services.service3Title',
    ageKey: 'services.service3Age',
    descKey: 'services.service3Desc',
    bgClass: 'bg-sky-50/80 border-sky-200/80 hover:bg-sky-100/60',
    badgeClass: 'bg-sky-100 text-sky-900 border-sky-300',
    iconBg: 'bg-sky-400 text-white',
    iconEmoji: '✨',
    accentColor: 'text-sky-600'
  },
  {
    id: 4,
    titleKey: 'services.service4Title',
    ageKey: 'services.service4Age',
    descKey: 'services.service4Desc',
    bgClass: 'bg-purple-50/80 border-purple-200/80 hover:bg-purple-100/60',
    badgeClass: 'bg-purple-100 text-purple-900 border-purple-300',
    iconBg: 'bg-purple-400 text-white',
    iconEmoji: '🌈',
    accentColor: 'text-purple-600'
  }
]
</script>

<template>
  <section id="services" class="py-16 lg:py-24 bg-slate-50/70 relative">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      
      <!-- Section Heading with Playful Doodles -->
      <div class="text-center max-w-3xl mx-auto mb-14 space-y-3">
        <div class="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-emerald-100 text-emerald-800 font-bold text-xs">
          <Sparkles class="w-3.5 h-3.5 text-emerald-600" />
          <span>{{ $t('services.badge') }}</span>
        </div>
        
        <h2 class="text-3xl sm:text-4xl lg:text-5xl font-black text-indigo-950 tracking-tight">
          {{ $t('services.title') }}
        </h2>
        
        <p class="text-base sm:text-lg text-slate-600 font-normal leading-relaxed">
          {{ $t('services.subtitle') }}
        </p>
      </div>

      <!-- 4 Pastel Cards Grid (Matching reference image layout & colors) -->
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <div
          v-for="program in defaultPrograms"
          :key="program.id"
          class="flex flex-col justify-between p-6 sm:p-7 rounded-[2rem] border-2 transition-all duration-300 hover:-translate-y-2 hover:shadow-xl relative group overflow-hidden"
          :class="program.bgClass"
        >
          <!-- Top Icon & Age Badge -->
          <div>
            <div class="flex items-center justify-between gap-2 mb-5">
              <div
                class="w-14 h-14 rounded-2xl flex items-center justify-center text-2xl shadow-md group-hover:scale-110 transition-transform"
                :class="program.iconBg"
              >
                <span>{{ program.iconEmoji }}</span>
              </div>
              <span
                class="px-3 py-1 rounded-full text-xs font-black border tracking-wide"
                :class="program.badgeClass"
              >
                {{ $t(program.ageKey) }}
              </span>
            </div>

            <!-- Card Title -->
            <h3 class="text-xl font-extrabold text-indigo-950 mb-3 tracking-tight">
              {{ $t(program.titleKey) }}
            </h3>

            <!-- Card Description -->
            <p class="text-sm text-slate-600 leading-relaxed font-medium">
              {{ $t(program.descKey) }}
            </p>
          </div>

          <!-- Bottom Action Link -->
          <div class="pt-6 mt-4 border-t border-slate-200/60">
            <button
              type="button"
              @click="modalStore.openBooking()"
              class="inline-flex items-center gap-2 text-sm font-bold transition-all group-hover:gap-3 cursor-pointer"
              :class="program.accentColor"
            >
              <span>{{ $t('services.learnMore') }}</span>
              <ArrowRight class="w-4 h-4 arrow-dir" />
            </button>
          </div>
        </div>
      </div>

    </div>
  </section>
</template>

// packages/themes/kindergarten-website-&-theme/src/components/Services.tsx
import React, { useState, useEffect } from 'react';
import { TranslationSchema, ServiceItem } from '../types';
import { Sparkles, ChevronRight, BookOpen } from 'lucide-react';

interface ServicesProps {
  t: TranslationSchema;
  onOpenBooking: () => void;
}

export const Services: React.FC<ServicesProps> = ({ t, onOpenBooking }) => {
  const [services, setServices] = useState<ServiceItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/services/public')
      .then((res) => (res.ok ? res.json() : []))
      .then((data) => {
        setServices(data);
        setLoading(false);
      })
      .catch(() => {
        setServices([]);
        setLoading(false);
      });
  }, []);

  return (
    <section id="services" className="py-16 md:py-24 bg-amber-50/50 relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-2xl mx-auto space-y-3 mb-12">
          <div className="inline-flex items-center space-x-2 gap-2 px-3 py-1 rounded-full bg-rose-100 text-rose-800 text-xs font-bold uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5" />
            <span>{t.services.title}</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold font-heading text-slate-800">
            {t.services.subtitle}
          </h2>
        </div>

        {/* Loading Skeleton */}
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {[1, 2, 3, 4, 5, 6].map((n) => (
              <div key={n} className="h-64 bg-slate-200/60 rounded-3xl animate-pulse"></div>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {services.map((item) => (
              <div
                key={item.id}
                className="card-playful bg-white p-6 border border-amber-100 shadow-sm flex flex-col justify-between hover:shadow-xl transition-all duration-300 group"
              >
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="w-14 h-14 rounded-2xl bg-amber-100 text-3xl flex items-center justify-center group-hover:scale-110 transition-transform">
                      {item.icon || '🎨'}
                    </div>
                    {item.ageGroup && (
                      <span className="px-3 py-1 rounded-full bg-teal-50 text-teal-700 text-xs font-bold border border-teal-100">
                        {item.ageGroup}
                      </span>
                    )}
                  </div>

                  <h3 className="text-xl font-bold font-heading text-slate-800 group-hover:text-rose-600 transition-colors">
                    {item.title}
                  </h3>

                  <p className="text-slate-600 text-sm leading-relaxed">
                    {item.description}
                  </p>
                </div>

                <div className="mt-6 pt-4 border-t border-slate-100 flex items-center justify-between">
                  <button
                    onClick={onOpenBooking}
                    className="text-xs font-bold text-amber-600 group-hover:text-rose-600 flex items-center space-x-1 gap-1 cursor-pointer"
                  >
                    <span>{t.services.viewDetails}</span>
                    <ChevronRight className="w-4 h-4" />
                  </button>
                  <BookOpen className="w-4 h-4 text-slate-300 group-hover:text-amber-500 transition-colors" />
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
};
