// packages/themes/nuxiox-ivory/app/components/sections/Team.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { Award, GraduationCap, CheckCircle2 } from 'lucide-vue-next';

interface ColleagueItem {
  id: number;
  image: string | null;
  title: string;
  subtitle: string | null;
  description: string | null;
  extra: { key: string; value: string }[];
}

const team = ref<ColleagueItem[]>([]);

onMounted(async () => {
  try {
    const res = await fetch('/api/colleagues/public');
    if (res.ok) {
      team.value = await res.json();
    }
  } catch (e) {
    console.error('Failed to load team', e);
  }
});
</script>

<template>
  <section class="py-20 bg-white dark:bg-slate-900 transition-colors">
    <div class="max-w-7xl mx-auto px-4 sm:px-8 space-y-16">
      
      <!-- Section Header -->
      <div class="max-w-2xl space-y-3">
        <span class="text-xs font-bold tracking-widest text-[#00C4DF] uppercase">Medical Team</span>
        <h2 class="text-4xl sm:text-5xl font-light text-slate-900 dark:text-white leading-tight">
          Board-certified <span class="font-bold">Specialists</span>
        </h2>
        <p class="text-sm text-slate-500">
          Our international team of oral surgeons, implantologists, and aesthetic dentists holds certifications from top European universities.
        </p>
      </div>

      <!-- Doctor Cards -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div 
          v-for="doc in team" 
          :key="doc.id"
          class="bg-slate-50 dark:bg-slate-800/60 rounded-3xl p-6 border border-slate-200/80 dark:border-slate-800 space-y-6 hover:shadow-xl transition-all"
        >
          <div class="relative aspect-square rounded-2xl overflow-hidden bg-slate-200 dark:bg-slate-700">
            <img 
              :src="doc.image || 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=800'" 
              :alt="doc.title"
              class="w-full h-full object-cover object-top"
              referrerPolicy="no-referrer"
            />
            <div class="absolute bottom-3 left-3 px-3 py-1 rounded-full bg-slate-950/80 text-white text-[11px] font-mono backdrop-blur">
              VERIFIED SPECIALIST
            </div>
          </div>

          <div class="space-y-2">
            <h3 class="text-xl font-bold text-slate-900 dark:text-white">
              {{ doc.title }}
            </h3>
            <p class="text-xs font-semibold text-[#00C4DF]">
              {{ doc.subtitle }}
            </p>
            <p class="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
              {{ doc.description }}
            </p>
          </div>

          <div v-if="doc.extra?.length" class="pt-2 border-t border-slate-200 dark:border-slate-700 space-y-2">
            <div 
              v-for="ex in doc.extra" 
              :key="ex.key"
              class="flex items-center gap-2 text-[11px] text-slate-500 dark:text-slate-400"
            >
              <GraduationCap class="w-3.5 h-3.5 text-[#00C4DF]" />
              <span>{{ ex.value }}</span>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>
</template>

// packages/themes/kindergarten-website-&-theme/src/components/Team.tsx
import React, { useState, useEffect } from 'react';
import { TranslationSchema, ColleagueItem } from '../types';
import { Sparkles, GraduationCap } from 'lucide-react';

interface TeamProps {
  t: TranslationSchema;
}

export const Team: React.FC<TeamProps> = ({ t }) => {
  const [colleagues, setColleagues] = useState<ColleagueItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/colleagues/public')
      .then((res) => (res.ok ? res.json() : []))
      .then((data) => {
        setColleagues(data);
        setLoading(false);
      })
      .catch(() => {
        setColleagues([]);
        setLoading(false);
      });
  }, []);

  return (
    <section id="team" className="py-16 md:py-24 bg-white relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto space-y-3 mb-12">
          <div className="inline-flex items-center space-x-2 gap-2 px-3 py-1 rounded-full bg-purple-100 text-purple-800 text-xs font-bold uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5" />
            <span>{t.team.title}</span>
          </div>
          <p className="text-slate-600 text-base sm:text-lg">
            {t.team.subtitle}
          </p>
        </div>

        {loading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {[1, 2, 3, 4].map((n) => (
              <div key={n} className="h-80 bg-slate-100 rounded-3xl animate-pulse"></div>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {colleagues.map((person) => (
              <div
                key={person.id}
                className="bg-white rounded-3xl overflow-hidden border border-amber-100 shadow-sm text-center p-6 space-y-4 hover:shadow-lg transition-all duration-300 hover:-translate-y-1"
              >
                <div className="relative w-28 h-28 mx-auto rounded-full overflow-hidden border-4 border-amber-200 shadow-inner">
                  <img
                    src={person.image || 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80'}
                    alt={person.name}
                    className="w-full h-full object-cover"
                  />
                  <div className="absolute bottom-0 right-0 bg-rose-500 text-white p-1 rounded-full text-xs shadow-md">
                    <GraduationCap className="w-3.5 h-3.5" />
                  </div>
                </div>

                <div>
                  <h3 className="font-bold text-lg font-heading text-slate-800">{person.name}</h3>
                  <p className="text-xs font-bold text-teal-600 uppercase tracking-wide mt-1">{person.role}</p>
                </div>

                {person.bio && (
                  <p className="text-xs text-slate-600 leading-relaxed line-clamp-3">
                    {person.bio}
                  </p>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
};
