// packages/themes/dental-clinic/app/components/sections/Testimonials.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { Star, MessageSquareQuote, ShieldCheck } from 'lucide-vue-next';

interface Testimonial {
  id: number;
  avatar: string | null;
  rating: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  name: string;
  role: string | null;
  content: string;
}

const testimonials = ref<Testimonial[]>([]);
const loading = ref(true);

const fetchTestimonials = async () => {
  try {
    loading.value = true;
    const res = await fetch('/api/testimonials/public');
    if (res.ok) {
      testimonials.value = await res.json();
    }
  } catch (err) {
    console.error('Error fetching testimonials:', err);
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  fetchTestimonials();
});
</script>

<template>
  <section id="testimonials" class="py-20 bg-white dark:bg-slate-950 border-t border-slate-200/60 dark:border-slate-800">
    <div class="max-w-7xl mx-auto px-4 sm:px-8">
      <!-- Section Header -->
      <div class="text-center max-w-3xl mx-auto mb-16 space-y-4">
        <div class="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-teal-100 dark:bg-teal-950 text-teal-700 dark:text-teal-300 text-xs font-bold uppercase tracking-wider">
          <MessageSquareQuote class="w-4 h-4" />
          <span>Verified Patient Reviews</span>
        </div>
        <h2 class="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
          Read Real Patient Experiences & Stories
        </h2>
        <p class="text-slate-600 dark:text-slate-300 text-base leading-relaxed">
          Nothing matters more to us than your comfort, health, and radiant smile confidence.
        </p>
      </div>

      <!-- Loading state -->
      <div v-if="loading" class="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div v-for="i in 4" :key="i" class="h-48 bg-slate-100 dark:bg-slate-900 rounded-2xl animate-pulse"></div>
      </div>

      <!-- Testimonial Cards -->
      <div v-else class="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div 
          v-for="item in testimonials" 
          :key="item.id"
          class="bg-slate-50 dark:bg-slate-900 p-8 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm relative space-y-4 flex flex-col justify-between"
        >
          <div class="space-y-3">
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-1 text-amber-400">
                <Star v-for="s in item.rating" :key="s" class="w-4 h-4 fill-amber-400" />
              </div>
              <span class="text-[10px] font-extrabold uppercase bg-teal-100 dark:bg-teal-950 text-teal-800 dark:text-teal-200 px-2 py-0.5 rounded border border-teal-200 dark:border-teal-800 flex items-center gap-1">
                <ShieldCheck class="w-3 h-3 text-teal-600" />
                Verified Patient
              </span>
            </div>

            <p class="text-slate-700 dark:text-slate-300 text-sm leading-relaxed italic">
              "{{ item.content }}"
            </p>
          </div>

          <div class="flex items-center gap-4 pt-4 border-t border-slate-200 dark:border-slate-800/80">
            <img 
              v-if="item.avatar" 
              :src="item.avatar" 
              :alt="item.name"
              class="w-12 h-12 rounded-full object-cover border-2 border-teal-500 shrink-0"
            />
            <div>
              <h4 class="font-bold text-slate-900 dark:text-white text-base">{{ item.name }}</h4>
              <p class="text-xs text-teal-600 dark:text-teal-400 font-semibold">{{ item.role }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

// packages/themes/kindergarten-website-&-theme/src/components/Testimonials.tsx
import React, { useState, useEffect } from 'react';
import { TranslationSchema, TestimonialItem } from '../types';
import { Sparkles, Star, Quote } from 'lucide-react';

interface TestimonialsProps {
  t: TranslationSchema;
}

export const Testimonials: React.FC<TestimonialsProps> = ({ t }) => {
  const [testimonials, setTestimonials] = useState<TestimonialItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/testimonials/public')
      .then((res) => (res.ok ? res.json() : []))
      .then((data) => {
        setTestimonials(data);
        setLoading(false);
      })
      .catch(() => {
        setTestimonials([]);
        setLoading(false);
      });
  }, []);

  return (
    <section id="testimonials" className="py-16 md:py-24 bg-amber-50/40 relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto space-y-3 mb-12">
          <div className="inline-flex items-center space-x-2 gap-2 px-3 py-1 rounded-full bg-amber-100 text-amber-800 text-xs font-bold uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5" />
            <span>{t.testimonials.title}</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold font-heading text-slate-800">
            {t.testimonials.subtitle}
          </h2>
        </div>

        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[1, 2, 3].map((n) => (
              <div key={n} className="h-48 bg-slate-200/60 rounded-3xl animate-pulse"></div>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((item) => (
              <div
                key={item.id}
                className="p-6 rounded-3xl bg-white border border-amber-100 shadow-sm flex flex-col justify-between space-y-4 hover:shadow-md transition-shadow relative"
              >
                <Quote className="absolute top-4 right-4 w-8 h-8 text-amber-100 -z-0" />

                <div className="space-y-3 relative z-10">
                  <div className="flex text-amber-400 space-x-1 gap-1">
                    {[...Array(item.rating || 5)].map((_, i) => (
                      <Star key={i} className="w-4 h-4 fill-amber-400 text-amber-400" />
                    ))}
                  </div>
                  <p className="text-slate-700 text-sm italic leading-relaxed">
                    "{item.content}"
                  </p>
                </div>

                <div className="flex items-center space-x-3 gap-3 pt-4 border-t border-slate-100">
                  <div className="w-10 h-10 rounded-full bg-amber-200 flex items-center justify-center font-bold text-amber-900 text-sm">
                    {item.name.charAt(0)}
                  </div>
                  <div>
                    <p className="font-bold text-slate-800 text-sm">{item.name}</p>
                    <p className="text-xs text-slate-500 font-medium">Kindergarten Parent</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
};
