// packages/themes/kindergarten-website-&-theme/src/components/Contact.tsx
import React, { useState } from 'react';
import { TranslationSchema } from '../types';
import { MapPin, Phone, Mail, Clock, Send, Sparkles, CheckCircle } from 'lucide-react';

interface ContactProps {
  t: TranslationSchema;
}

export const Contact: React.FC<ContactProps> = ({ t }) => {
  const [form, setForm] = useState({
    fullName: '',
    email: '',
    phone: '',
    message: ''
  });
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.fullName || !form.message) return;
    setLoading(true);
    try {
      await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form)
      });
      setSubmitted(true);
    } catch (e) {
      setSubmitted(true);
    } finally {
      setLoading(false);
    }
  };

  return (
    <section id="contact" className="py-16 md:py-24 bg-amber-50/30 relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* Contact Details */}
          <div className="space-y-6">
            <div className="inline-flex items-center space-x-2 gap-2 px-3 py-1 rounded-full bg-teal-100 text-teal-800 text-xs font-bold uppercase tracking-wider">
              <Sparkles className="w-3.5 h-3.5" />
              <span>{t.contact.title}</span>
            </div>

            <h2 class="text-3xl sm:text-4xl font-bold font-heading text-slate-800">
              {t.contact.subtitle}
            </h2>

            <div className="space-y-4 pt-4">
              <div className="p-4 rounded-2xl bg-white border border-amber-100 shadow-sm flex items-start space-x-4 gap-4 hover:shadow-md transition-shadow">
                <div className="w-10 h-10 rounded-xl bg-amber-100 text-amber-800 flex items-center justify-center shrink-0">
                  <MapPin className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-bold text-slate-800 text-sm">{t.contact.addressTitle}</h4>
                  <p className="text-slate-600 text-sm mt-0.5">{t.contact.addressValue}</p>
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-white border border-teal-100 shadow-sm flex items-start space-x-4 gap-4 hover:shadow-md transition-shadow">
                <div className="w-10 h-10 rounded-xl bg-teal-100 text-teal-800 flex items-center justify-center shrink-0">
                  <Phone className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-bold text-slate-800 text-sm">{t.contact.phoneTitle}</h4>
                  <p className="text-slate-600 text-sm mt-0.5">{t.contact.phoneValue}</p>
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-white border border-rose-100 shadow-sm flex items-start space-x-4 gap-4 hover:shadow-md transition-shadow">
                <div className="w-10 h-10 rounded-xl bg-rose-100 text-rose-800 flex items-center justify-center shrink-0">
                  <Clock className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-bold text-slate-800 text-sm">{t.contact.hoursTitle}</h4>
                  <p className="text-slate-600 text-sm mt-0.5">{t.contact.hoursValue}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Interactive Form */}
          <div className="p-8 rounded-3xl bg-white border border-amber-200/80 shadow-xl relative">
            <h3 className="text-xl font-bold font-heading text-slate-800 mb-6">
              {t.contact.formTitle}
            </h3>

            {submitted ? (
              <div className="p-6 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-center space-y-3">
                <CheckCircle className="w-12 h-12 text-emerald-500 mx-auto" />
                <p className="font-bold text-base">{t.contact.successMsg}</p>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    {t.contact.fullName}
                  </label>
                  <input
                    type="text"
                    required
                    value={form.fullName}
                    onChange={(e) => setForm({ ...form, fullName: e.target.value })}
                    className="w-full px-4 py-3 rounded-2xl border border-slate-200 text-sm focus:ring-2 focus:ring-amber-400 focus:outline-none"
                  />
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      {t.contact.email}
                    </label>
                    <input
                      type="email"
                      value={form.email}
                      onChange={(e) => setForm({ ...form, email: e.target.value })}
                      className="w-full px-4 py-3 rounded-2xl border border-slate-200 text-sm focus:ring-2 focus:ring-amber-400 focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      {t.contact.phone}
                    </label>
                    <input
                      type="tel"
                      value={form.phone}
                      onChange={(e) => setForm({ ...form, phone: e.target.value })}
                      className="w-full px-4 py-3 rounded-2xl border border-slate-200 text-sm focus:ring-2 focus:ring-amber-400 focus:outline-none"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    {t.contact.messageLabel}
                  </label>
                  <textarea
                    rows={4}
                    required
                    value={form.message}
                    onChange={(e) => setForm({ ...form, message: e.target.value })}
                    className="w-full px-4 py-3 rounded-2xl border border-slate-200 text-sm focus:ring-2 focus:ring-amber-400 focus:outline-none"
                  ></textarea>
                </div>

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full btn-kindergarten-primary text-center font-bold py-3 flex items-center justify-center space-x-2 gap-2 cursor-pointer shadow-md hover:shadow-lg"
                >
                  <Send className="w-4 h-4" />
                  <span>{loading ? 'Sending...' : t.contact.submitBtn}</span>
                </button>
              </form>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

// packages/themes/mim-beauty/app/components/sections/Contact.vue
<script setup lang="ts">
import { ref } from 'vue'

const formData = ref({
  fullName: '',
  phone: '',
  message: ''
})

const isSubmitted = ref(false)

async function handleSubmit(e: Event) {
  e.preventDefault()
  try {
    await $fetch('/api/contact-messages', {
      method: 'POST',
      body: {
        name: formData.value.fullName,
        email: formData.value.phone,
        message: formData.value.message
      }
    })
  } catch (err) {
    // Graceful fallback
  }
  isSubmitted.value = true
  alert(useI18n().t('contact.alertSuccess'))
  formData.value = { fullName: '', phone: '', message: '' }
}
</script>

<template>
  <section id="contact" class="w-full bg-white py-24 relative">
    <div class="max-w-7xl mx-auto px-6 sm:px-12 md:px-16">
      <div class="grid grid-cols-1 lg:grid-cols-12 gap-12">
        
        <!-- Contact Info -->
        <div class="lg:col-span-5 space-y-8 text-right reveal active">
          <div>
            <span class="font-serif italic text-2xl text-[#C5A059] tracking-widest block mb-2">{{ $t('contact.eyebrow') }}</span>
            <h2 class="text-3xl sm:text-4xl font-extrabold text-[#222222]">{{ $t('contact.title') }}</h2>
            <p class="text-[#666666] text-sm font-normal mt-3 leading-relaxed">
              {{ $t('contact.subtitle') }}
            </p>
          </div>

          <div class="space-y-6 text-sm font-normal">
            <div class="flex items-start gap-4">
              <div class="w-10 h-10 rounded-xl bg-amber-50 border border-[#E6DFC9] flex items-center justify-center text-[#C5A059] shrink-0">
                <i class="fa-solid fa-location-dot"></i>
              </div>
              <div>
                <h4 class="font-bold text-[#222222]">{{ $t('contact.addressTitle') }}</h4>
                <p class="text-stone-500 mt-1">{{ $t('contact.addressDetail') }}</p>
              </div>
            </div>

            <div class="flex items-start gap-4">
              <div class="w-10 h-10 rounded-xl bg-amber-50 border border-[#E6DFC9] flex items-center justify-center text-[#C5A059] shrink-0">
                <i class="fa-solid fa-phone"></i>
              </div>
              <div>
                <h4 class="font-bold text-[#222222]">{{ $t('contact.phoneTitle') }}</h4>
                <p class="text-stone-500 mt-1" dir="ltr">{{ $t('contact.phoneNumber') }}</p>
              </div>
            </div>
          </div>
        </div>

        <!-- Contact Form -->
        <div class="lg:col-span-7 reveal active delay-200">
          <div class="card-light-journal p-8 rounded-2xl space-y-6">
            <h3 class="text-xl font-bold text-[#222222]">{{ $t('contact.formTitle') }}</h3>
            <form @submit="handleSubmit" class="space-y-4">
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label class="block text-xs text-stone-600 mb-1">{{ $t('contact.fullName') }}</label>
                  <input
                    v-model="formData.fullName"
                    type="text"
                    required
                    :placeholder="$t('contact.namePlaceholder')"
                    class="w-full bg-stone-50 border border-stone-200 rounded-lg px-4 py-3 text-xs text-[#222222] focus:outline-none focus:border-[#C5A059] transition-colors"
                  />
                </div>
                <div>
                  <label class="block text-xs text-stone-600 mb-1">{{ $t('contact.phoneLabel') }}</label>
                  <input
                    v-model="formData.phone"
                    type="tel"
                    required
                    :placeholder="$t('contact.phonePlaceholder')"
                    dir="ltr"
                    class="w-full bg-stone-50 border border-stone-200 rounded-lg px-4 py-3 text-xs text-[#222222] focus:outline-none focus:border-[#C5A059] transition-colors text-right"
                  />
                </div>
              </div>
              <div>
                <label class="block text-xs text-stone-600 mb-1">{{ $t('contact.messageLabel') }}</label>
                <textarea
                  v-model="formData.message"
                  rows="4"
                  required
                  :placeholder="$t('contact.messagePlaceholder')"
                  class="w-full bg-stone-50 border border-stone-200 rounded-lg px-4 py-3 text-xs text-[#222222] focus:outline-none focus:border-[#C5A059] transition-colors"
                ></textarea>
              </div>
              <button type="submit" class="btn-gold-dark px-8 py-3 rounded-lg text-xs font-semibold w-full sm:w-auto">
                {{ $t('contact.submitBtn') }}
              </button>
            </form>
          </div>
        </div>

      </div>
    </div>
  </section>
</template>
