// packages/themes/kindergarten-website-&-theme/src/components/Blog.tsx
import React, { useState, useEffect } from 'react';
import { TranslationSchema, BlogPostItem } from '../types';
import { Sparkles, ArrowRight, Search, Calendar as CalendarIcon } from 'lucide-react';

interface BlogProps {
  t: TranslationSchema;
}

export const Blog: React.FC<BlogProps> = ({ t }) => {
  const [posts, setPosts] = useState<BlogPostItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    fetch('/api/blog/posts/recent')
      .then((res) => (res.ok ? res.json() : []))
      .then((data) => {
        setPosts(data);
        setLoading(false);
      })
      .catch(() => {
        setPosts([]);
        setLoading(false);
      });
  }, []);

  const filteredPosts = posts.filter(
    (p) =>
      p.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (p.excerpt && p.excerpt.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  return (
    <section id="blog" className="py-16 md:py-24 bg-white relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto space-y-3 mb-10">
          <div className="inline-flex items-center space-x-2 gap-2 px-3 py-1 rounded-full bg-rose-100 text-rose-800 text-xs font-bold uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5" />
            <span>{t.blog.title}</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold font-heading text-slate-800">
            {t.blog.subtitle}
          </h2>
        </div>

        {/* Search Bar */}
        <div className="max-w-md mx-auto mb-10 relative">
          <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder={t.blog.searchPlaceholder}
            className="w-full pl-10 pr-4 py-2.5 rounded-full border border-amber-200 text-xs font-medium focus:ring-2 focus:ring-rose-400 focus:outline-none bg-amber-50/20"
          />
        </div>

        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[1, 2, 3].map((n) => (
              <div key={n} className="h-80 bg-slate-100 rounded-3xl animate-pulse"></div>
            ))}
          </div>
        ) : filteredPosts.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {filteredPosts.map((post) => (
              <article
                key={post.id}
                className="bg-white rounded-3xl overflow-hidden border border-rose-100 shadow-sm flex flex-col justify-between hover:shadow-lg transition-all duration-300 group"
              >
                <div>
                  <div className="aspect-16/9 bg-slate-100 overflow-hidden relative">
                    <img
                      src={post.featuredImage || 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80'}
                      alt={post.title}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                    <div className="absolute top-3 left-3 bg-white/90 backdrop-blur-md px-3 py-1 rounded-full text-[10px] font-bold text-rose-600 flex items-center space-x-1 gap-1">
                      <CalendarIcon className="w-3 h-3" />
                      <span>{post.createdAt}</span>
                    </div>
                  </div>
                  <div className="p-6 space-y-3">
                    <h3 className="font-bold text-lg font-heading text-slate-800 line-clamp-2 group-hover:text-rose-600 transition-colors">
                      {post.title}
                    </h3>
                    <p className="text-slate-600 text-xs leading-relaxed line-clamp-3">
                      {post.excerpt}
                    </p>
                  </div>
                </div>

                <div className="p-6 pt-0">
                  <span className="text-xs font-bold text-rose-600 hover:text-rose-700 flex items-center space-x-1.5 gap-1.5 cursor-pointer">
                    <span>{t.blog.readMore}</span>
                    <ArrowRight className="w-4 h-4" />
                  </span>
                </div>
              </article>
            ))}
          </div>
        ) : (
          <div className="text-center py-12 text-slate-500 text-sm font-medium">
            {t.blog.notFound}
          </div>
        )}
      </div>
    </section>
  );
};

// packages/themes/kids-dental/app/components/sections/Blog.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { Sparkles, Calendar, ArrowRight, BookOpen, Send, Check } from 'lucide-vue-next'

const apiPosts = ref<any[]>([])
const newsletterEmail = ref('')
const isSubscribed = ref(false)

async function fetchBlogPosts() {
  try {
    const res = await fetch('/api/blog/posts/recent')
    if (res.ok) {
      const data = await res.json()
      if (Array.isArray(data) && data.length > 0) {
        apiPosts.value = data
      }
    }
  } catch (e) {
    // Fallback to translated posts
  }
}

function handleSubscribe() {
  if (newsletterEmail.value.trim()) {
    isSubscribed.value = true
    setTimeout(() => {
      newsletterEmail.value = ''
    }, 4000)
  }
}

onMounted(() => {
  fetchBlogPosts()
})

const defaultArticles = [
  {
    id: 1,
    titleKey: 'blog.post1Title',
    categoryKey: 'blog.post1Category',
    dateKey: 'blog.post1Date',
    excerptKey: 'blog.post1Excerpt',
    img: 'https://images.unsplash.com/photo-1593100126453-19b562a800c1?auto=format&fit=crop&w=600&q=80',
    tagColor: 'bg-amber-100 text-amber-900'
  },
  {
    id: 2,
    titleKey: 'blog.post2Title',
    categoryKey: 'blog.post2Category',
    dateKey: 'blog.post2Date',
    excerptKey: 'blog.post2Excerpt',
    img: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=600&q=80',
    tagColor: 'bg-emerald-100 text-emerald-900'
  },
  {
    id: 3,
    titleKey: 'blog.post3Title',
    categoryKey: 'blog.post3Category',
    dateKey: 'blog.post3Date',
    excerptKey: 'blog.post3Excerpt',
    img: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=600&q=80',
    tagColor: 'bg-purple-100 text-purple-900'
  }
]
</script>

<template>
  <section id="blog" class="py-16 lg:py-24 bg-slate-50 relative overflow-hidden">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      
      <!-- Section Header -->
      <div class="text-center max-w-3xl mx-auto mb-14 space-y-3">
        <div class="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-amber-100 text-amber-800 font-bold text-xs">
          <BookOpen class="w-3.5 h-3.5 text-amber-600" />
          <span data-i18n="blog.badge">{{ $t('blog.badge') }}</span>
        </div>
        
        <h2 data-i18n="blog.title" class="text-3xl sm:text-4xl lg:text-5xl font-black text-indigo-950 tracking-tight">
          {{ $t('blog.title') }}
        </h2>
        
        <p data-i18n="blog.subtitle" class="text-base sm:text-lg text-slate-600 font-normal leading-relaxed">
          {{ $t('blog.subtitle') }}
        </p>
      </div>

      <!-- Articles Grid -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
        <article
          v-for="article in defaultArticles"
          :key="article.id"
          class="bg-white rounded-[2rem] p-4 border border-slate-200/70 shadow-md flex flex-col justify-between hover:shadow-xl hover:-translate-y-1.5 transition-all duration-300 group"
        >
          <div>
            <!-- Thumbnail Frame -->
            <div class="relative h-48 sm:h-52 rounded-[1.6rem] overflow-hidden mb-4">
              <img
                :src="article.img"
                :alt="$t(article.titleKey)"
                class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                loading="lazy"
              />
              <span
                class="absolute top-3 left-3 px-3 py-1 rounded-full text-xs font-black shadow-xs"
                :class="article.tagColor"
              >
                {{ $t(article.categoryKey) }}
              </span>
            </div>

            <!-- Meta & Title -->
            <div class="p-2 space-y-2 text-start">
              <div class="flex items-center gap-2 text-xs font-semibold text-slate-500">
                <Calendar class="w-3.5 h-3.5 text-slate-400" />
                <span>{{ $t(article.dateKey) }}</span>
              </div>

              <h3 class="text-lg font-black text-indigo-950 tracking-tight leading-snug group-hover:text-indigo-600 transition-colors">
                {{ $t(article.titleKey) }}
              </h3>

              <p class="text-xs sm:text-sm text-slate-600 font-normal leading-relaxed">
                {{ $t(article.excerptKey) }}
              </p>
            </div>
          </div>

          <!-- Bottom Read More -->
          <div class="p-2 pt-4 border-t border-slate-100 flex items-center justify-between text-xs font-bold text-indigo-600">
            <span data-i18n="blog.readMore">{{ $t('blog.readMore') }}</span>
            <ArrowRight class="w-4 h-4 group-hover:translate-x-1 transition-transform arrow-dir" />
          </div>
        </article>
      </div>

      <!-- Newsletter Bar (Exact component from reference image!) -->
      <div class="bg-gradient-to-r from-amber-100/90 via-amber-50 to-orange-100/80 rounded-[2.5rem] p-6 sm:p-8 lg:p-10 border-2 border-amber-300/80 shadow-xl relative overflow-hidden">
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-6 items-center">
          
          <!-- Left: Envelope sticker & Heading -->
          <div class="lg:col-span-6 flex items-center gap-4 sm:gap-6 text-start">
            <div class="w-16 h-16 sm:w-20 sm:h-20 rounded-2xl bg-amber-400 text-indigo-950 flex items-center justify-center text-3xl sm:text-4xl shadow-md shrink-0">
              💌
            </div>
            <div class="space-y-1">
              <h3 data-i18n="newsletter.title" class="text-xl sm:text-2xl font-black text-indigo-950 tracking-tight">
                {{ $t('newsletter.title') }}
              </h3>
              <p data-i18n="newsletter.subtitle" class="text-xs sm:text-sm text-slate-600 font-medium">
                {{ $t('newsletter.subtitle') }}
              </p>
            </div>
          </div>

          <!-- Right: Input & Subscribe button -->
          <div class="lg:col-span-6">
            <form @submit.prevent="handleSubscribe" class="flex flex-col sm:flex-row gap-3">
              <input
                v-model="newsletterEmail"
                type="email"
                required
                :placeholder="$t('newsletter.placeholder')"
                class="flex-1 px-5 py-3.5 rounded-full bg-white border border-amber-300 text-slate-800 text-xs sm:text-sm font-medium focus:outline-hidden focus:ring-2 focus:ring-amber-500 shadow-xs"
              />
              <button
                type="submit"
                class="inline-flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-extrabold text-xs sm:text-sm px-6 py-3.5 rounded-full shadow-md active:scale-95 transition-all shrink-0 cursor-pointer"
              >
                <span data-i18n="newsletter.subscribeBtn">{{ $t('newsletter.subscribeBtn') }}</span>
                <Send class="w-4 h-4 arrow-dir" />
              </button>
            </form>
            <div v-if="isSubscribed" class="mt-2 text-xs font-bold text-emerald-700 flex items-center gap-1.5 animate-fade-in">
              <Check class="w-4 h-4" />
              <span data-i18n="newsletter.thankYou">{{ $t('newsletter.thankYou') }}</span>
            </div>
          </div>

        </div>
      </div>

    </div>
  </section>
</template>
